### ISSUE TITLE
Link to the Atom feed in <head>

### ISSUE THREAD

**Issue by hrs** [albertyw/albertyw.com#58]
Folks who use syndication often configure their browsers to display a link to a site's feed in the search bar, which shows up like:

![2020-06-01-080609_194x100_scrot](https://user-images.githubusercontent.com/278853/83417053-cc11b080-a3de-11ea-970a-2378a389728c.png)

That works iff the website links to the feed in its header, like so:

``` html
<head>
  [...]
  <link href="/atom.xml" rel="alternate" title="Albert Wang" type="application/atom+xml" />
  [...]
</head>
```

Might be nice!

**Comment by albertyw** [comment]
Fixed in abc14fc
