### ISSUE TITLE
Atom entries ought to link to the associated page

### ISSUE THREAD

**Issue by hrs** [albertyw/albertyw.com#59]
Atom entries often include link to where the associated content can be found on the Web. That's nice when, for example, a reader would prefer to read an article in their browser instead of in their feed reader, since they can just hit a key to open the page.

There's currently aren't links associated with the entries in the site's feed, but it'd be easy to add them! You'd just need to include a `link` tag with the correct URL when generating the feed, like so:

``` html
<entry>
  [...]
  <title>Switching From Go Dep to Go Mod</title>
  <link href="https://www.albertyw.com/note/go-dep-mod"/>
  [...]
</entry>
```

**Comment by albertyw** [comment]
Fixed in cb43110
